language: perl
perl:
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
before_install:
  - cpanm --notest Devel::Cover::Report::Coveralls
  - cpanm --notest Module::Build
  - cpanm --notest Test::Pod
  - cpanm --notest Pod::Coverage
  - cpanm --notest Test::Pod::Coverage
script:
  - perl Build.PL && ./Build build && cover -test -report coveralls
