language: perl
perl:
  - "5.14"
before_install:
  - cpanm Devel::Cover::Report::Coveralls
  - cpanm Module::Build
  - cpanm Test::Pod
  - cpanm Pod::Coverage
  - cpanm Test::Pod::Coverage
script:
  perl Build.PL
  ./Build build
  cover -test -report coveralls
